" pathogen
call pathogen#runtime_append_all_bundles()

" vim settings
set number
syntax on
filetype on
filetype plugin indent on

" text formatting
set backspace=2
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab
set textwidth=80
set hlsearch
set incsearch

" switch tabs
map = gt<CR>
map - gT<CR>

" command-t
let g:CommandTMaxHeight=10

" mappings
nnoremap <F5> :GundoToggle<CR>
nnoremap <silent> <F9> :TagbarToggle<CR>

" solarized colors
set t_Co=16
let g:solarized_termcolors=16
set background=dark
colorscheme solarized 

" highlight current line
:hi CursorLine   cterm=NONE
set cursorline
